name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: checkout code
      - name: List files
        run: ls
      - name: Build Docker image
        run: docker build .
      - name: List Docker images
        run: docker images
      - name: Push Docker image
        run: docker push
