name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get current version
        id: get_version
        run: echo "CURRENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          NEW_VERSION=$((CURRENT_VERSION + 1))
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo $NEW_VERSION > VERSION

      - name: Commit new version
        run: |
          git add VERSION
          git commit -m "Increment version to $NEW_VERSION"
          git push origin main

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/bellimage:"$NEW_VERSION" .

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/:"${{ env.NEW_VERSION }}"
